---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: 11.6.2

suites:
- name: gcc
  run_list:
  - recipe[minitest-handler]
  - recipe[gcc_test::default]
  attributes: {}
